### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by Jaskaran-smtc** [SouravJohar/python-app-with-electron-gui#2]
Hi Sourav I am getting error when I am trying to use Weather forecast when I  input  city I get following error

`weather.js:13 Uncaught TypeError: python is not a constructor
    at get_weather (weather.js:13)
    at HTMLButtonElement.onclick (weather.html:20)`

**Comment by axwax** [comment]
I'm running into the same error.
Others have had similar problems with python-shell recently too: https://github.com/extrabacon/python-shell/issues/142

**Comment by prince737** [comment]
Found any solutions? Stuck with the same issue. I have also opened an issue at python-shell repo.

**Comment by gregology** [comment]
Same here :(

**Comment by bsegot** [comment]
The guy who maintains python-shell answered this issue at the bottom of this other tutorial:

https://ourcodeworld.com/articles/read/286/how-to-execute-a-python-script-and-retrieve-output-data-and-errors-in-node-js

He says to replace  
var PythonShell = require('python-shell') 
by 
var {PythonShell} = require('python-shell')

**Comment by SouravJohar** [comment]
Fixed this in the latest commit.
